-- Schema do Lume (PostgreSQL). Idempotente: rodar de novo não quebra nada.
-- Aplicado por `npm run db:setup`.

CREATE TABLE IF NOT EXISTS users (
  id            integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text        NOT NULL,
  password_hash text        NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- No SQLite o username era UNIQUE COLLATE NOCASE. O equivalente no Postgres é
-- um índice único sobre lower(username) — e é ele que garante que "Pedro" e
-- "pedro" não virem duas contas.
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower ON users (lower(username));

-- Mapa do Mês: os 7 hábitos de cada mês (slot 1..7)
CREATE TABLE IF NOT EXISTS habits (
  user_id   integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  month_key text    NOT NULL,            -- 'YYYY-MM'
  slot      integer NOT NULL,            -- 1..7
  name      text    NOT NULL DEFAULT '',
  PRIMARY KEY (user_id, month_key, slot)
);

-- Mapa do Mês: marcações do anel radial
CREATE TABLE IF NOT EXISTS habit_marks (
  user_id   integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  month_key text    NOT NULL,
  slot      integer NOT NULL,
  day       integer NOT NULL,            -- 1..31
  PRIMARY KEY (user_id, month_key, slot, day)
);

-- Planner Diário: cabeçalho do dia
CREATE TABLE IF NOT EXISTS days (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date    text    NOT NULL,              -- 'YYYY-MM-DD'
  notes   text    NOT NULL DEFAULT '',
  rating  integer,                       -- 1..5 (carinhas)
  PRIMARY KEY (user_id, date)
);

-- Planner Diário: tarefas ('normal' | 'inegociavel')
CREATE TABLE IF NOT EXISTS tasks (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id  integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date     text    NOT NULL,
  kind     text    NOT NULL,
  text     text    NOT NULL,
  done     integer NOT NULL DEFAULT 0,
  position integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS tasks_by_day ON tasks (user_id, date, kind, position);

-- Mapa do Ano
CREATE TABLE IF NOT EXISTS years (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  year    integer NOT NULL,
  metas   text    NOT NULL DEFAULT '',
  PRIMARY KEY (user_id, year)
);

CREATE TABLE IF NOT EXISTS year_marks (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  year    integer NOT NULL,
  month   integer NOT NULL,              -- 1..12
  day     integer NOT NULL,              -- 1..31
  PRIMARY KEY (user_id, year, month, day)
);
